/**
 * Things I Learned in March 2026
 */

import ShareButton from '../../components/ShareButton/ShareButton'

export const meta = {
  title: 'Things I Learned in March 2026',
  date: '2026-04-02',
  slug: 'things-i-learned-in-march-2026',
  preview:
    'March was a very eventful month for me, from major life milestones to lessons in software engineering, AI tools, and building my first RAG app.',
}

export default function ThingsILearnedInMarch2026Article() {
  return (
    <article className="article">
      <header className="article__header">
        <div className="article__header-row">
          <h2 className="article__title">{meta.title}</h2>
          <ShareButton />
        </div>
        <time className="article__date" dateTime={meta.date}>
          {meta.date}
        </time>
      </header>

      <div className="article__body">
        <p>
          March has been a very eventful month for me. I got assigned my first big feature at my new job, Ramadan ended and I had my second born child. This month felt as though a few months went by, but I learned so much each day. As a father, husband and software engineer, I&apos;m always learning something new every day, and I would like to share what I&apos;ve learned in March, now that we&apos;re in April.
        </p>

        <ul>
          <li>
            Software engineering is evolving due to the rise of AI tools such as Cursor and Claude Code. Be an orchestrator, guide the LLM on what code changes to make and question the approach that it&apos;s taking. This will lead to less headaches and doom loops.
          </li>
          <li>
            Took the leap to create a middleware service that would allow non-playable characters (NPCs) to be more intelligent in video games. It&apos;s currently in development. This is my first RAG app. RAG is short for retrieval-augmented generation.
            <figure className="article__figure">
              <img
                src="/assets/miscellaneous/npc_profiles.png"
                alt="NPC profile cards from an intelligent middleware service concept"
                className="article__img"
              />
              <figcaption className="article__figcaption">
                Early NPC profiles from the middleware service in development.
              </figcaption>
            </figure>
          </li>
          <li>
            There is a neat command to generate technical diagrams based on the architecture of an app. First, ask your LLM to generate a Mermaid diagram file. Mermaid is a text-based diagramming language which renders into visual diagrams. It&apos;s pretty neat. Here is the command to generate the diagrams from the Mermaid diagram file:
            <ul>
              <li>
                If you don&apos;t have Mermaid installed, run this in your CLI:{' '}
                <code>npm install -g @mermaid-js/mermaid-cli</code>
              </li>
              <li>
                Once you have Mermaid installed, run this:{' '}
                <code>mmdc -i ARCHITECTURE.md -o diagram.png</code>
              </li>
              <li>
                Basically, <code>ARCHITECTURE.md</code> is the architecture file that&apos;s generated by the LLM, and the <code>mmdc</code> command allows the diagrams to be generated from that architecture file.
              </li>
            </ul>
            <figure className="article__figure">
              <img
                src="/assets/miscellaneous/mermaid-diagram.png"
                alt="Mermaid architecture diagram generated from a Mermaid file"
                className="article__img"
              />
              <figcaption className="article__figcaption">
                Example diagram generated from a Mermaid architecture file.
              </figcaption>
            </figure>
          </li>
          <li>
            Not related to computers, but I recently got a surround sound system for my game room and learned how the wires get connected to the receiver. The sound quality is a game changer. Just make sure you don&apos;t misplace the red and black copper wires or the motherboard can melt!
            <figure className="article__figure">
              <img
                src="/assets/miscellaneous/sound_system.JPG"
                alt="Surround sound system setup in a game room"
                className="article__img"
              />
              <figcaption className="article__figcaption">
                New surround sound setup in my game room.
              </figcaption>
            </figure>
          </li>
          <li>
            Last but not least, I&apos;m now a father of 2, so I&apos;m working on getting better at managing everything by adding everything on Notion, which makes everything look less overwhelming and easy to tackle.
          </li>
        </ul>

        <p>Thank you for reading and hope you have a great April!</p>
      </div>
    </article>
  )
}
